env:
  - GO111MODULE=on

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/gost
    ldflags:
      - '-s -w'
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}_v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    format: tar.gz
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: false
    replacements:
      amd64: 64-bit
      386: 32-bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
release:
  draft: true
  prerelease: auto
  name_template: '{{.ProjectName}}-v{{.Version}}-{{.Date}}'